#!/bin/bash

REQ=requirements.txt
BASE_DIR="./"
COUNT=4
SEARCH_DIM=0

function create {
	echo "Creating new virtual environment..@($BASE_DIR)"
	python -m venv "${BASE_DIR}venv"
	activate
}

function activate {
	echo "$(tput bold)activating venv @($BASE_DIR) $(tput sgr0)"
	source "${BASE_DIR}venv/bin/activate"
	echo "Virtual environment up and running."
}

function up_search {
	SEARCH_DIM=$((SEARCH_DIM+1))
	if [ $SEARCH_DIM -eq $COUNT ]; then
		return
	fi
	echo "Searching for venv @($BASE_DIR)"
	if [ -d "${BASE_DIR}venv" ]; then
		activate
	else
		BASE_DIR="../$BASE_DIR"	
		up_search
	fi
}

if [ $# -ne 0 ]; then
	if [ $1 == "up" ]; then
		echo "Checking in upper directories..."
		BASE_DIR="../"
		up_search 
	fi
else
	if [ -d 'venv' ]; then
		echo "Using 'venv' as virtual environment"
		source "${BASE_DIR}venv/bin/activate"
	else
		create
		if [ $# -eq 0 ]; then 	
				if [ -f "$REQ" ];then
						read -p "Do you want to install requirements.txt?(y/n)" CHOICE
						if [ $CHOICE == "y" ]; then 
								echo -e "$(tput bold)Installing dependencies....$(tput sgr0)"
								pip install -r requirements.txt
						fi
				fi
		fi
	fi
fi
